/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.11
 * Generated at: 2017-06-29 14:57:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.templates;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-3.2.5.RELEASE.jar", Long.valueOf(1498740093009L));
    _jspx_dependants.put("jar:file:/C:/Users/Moon/Desktop/Saiden/Employment/java-kosta/WAS/final-tomcat/webapps/YOLOWA_FINAL/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1494128633492L));
    _jspx_dependants.put("jar:file:/C:/Users/Moon/Desktop/Saiden/Employment/java-kosta/WAS/final-tomcat/webapps/YOLOWA_FINAL/WEB-INF/lib/spring-security-taglibs-3.2.5.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1408068574000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifNotGranted;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifAnyGranted;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifNotGranted = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifAnyGranted = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifNotGranted.release();
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifAnyGranted.release();
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css\">\r\n");
      out.write("<script src=\"//code.jquery.com/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/ui/1.11.4/jquery-ui.min.js\"></script>\r\n");
      out.write("<!-- 알림창 CDN -->\r\n");
      out.write("<script src=\"//cdn.jsdelivr.net/alertifyjs/1.7.1/alertify.min.js\"></script><!-- JavaScript -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//cdn.jsdelivr.net/alertifyjs/1.7.1/css/alertify.min.css\"/><!-- CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//cdn.jsdelivr.net/alertifyjs/1.7.1/css/themes/default.min.css\"/><!-- Default theme -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//cdn.jsdelivr.net/alertifyjs/1.7.1/css/themes/semantic.min.css\"/><!-- Semantic UI theme -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//cdn.jsdelivr.net/alertifyjs/1.7.1/css/themes/bootstrap.min.css\"/><!-- Bootstrap theme -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\"#searhAll\").click(function(){\r\n");
      out.write("\t\t\tif($.trim($(\"#keywordAll\").val())==\"\"){\r\n");
      out.write("\t\t\t\talert(\"검색어를 입력하세요\");\r\n");
      out.write("\t\t\t\t$(\"#keywordAll\").focus();\r\n");
      out.write("\t\t\t\treturn ;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tlocation.href = \"searchListByKeyword.do?keyword=\"+$.trim($(\"#keywordAll\").val());\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}); // click(searhAll)\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$( \"#keywordAll\" ).autocomplete({\r\n");
      out.write("\t        source : function( request, response ) {\r\n");
      out.write("\t             $.ajax({\r\n");
      out.write("\t                    type: \"get\",\r\n");
      out.write("\t                    url: \"autoKeyword.do\",\r\n");
      out.write("\t                    dataType: \"json\",\r\n");
      out.write("\t                    data: \"keyword=\"+$.trim($(\"#keywordAll\").val()),\r\n");
      out.write("\t                    success: function(data) {\r\n");
      out.write("\t                        response(\r\n");
      out.write("\t                            $.map(data, function(item) {\r\n");
      out.write("\t                                return {\r\n");
      out.write("\t                                    label: item.KEYWORD,\r\n");
      out.write("\t                                    value: item.KEYWORD\r\n");
      out.write("\t                                } // return\r\n");
      out.write("\t                            }) // map\r\n");
      out.write("\t                        ); // response\r\n");
      out.write("\t                    } // success\r\n");
      out.write("\t               }); // ajax\r\n");
      out.write("\t            }, // source\r\n");
      out.write("\t    });\t// autocomplete\r\n");
      out.write("\t});\t// function\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write(".alertify-notifier .ajs-message.ajs-success{\r\n");
      out.write("\t  background-color: #2196F3;\r\n");
      out.write("      color: white;\r\n");
      out.write("}\r\n");
      out.write("#toTop {\r\n");
      out.write("\tz-index: 1030;\r\n");
      out.write("\twidth: 70px;\r\n");
      out.write("\theight: 70px;\r\n");
      out.write("\tborder: 2px solid #72bbf8;\r\n");
      out.write("\tbackground: #72bbf8;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tbottom: 50px;\r\n");
      out.write("\tright: 50px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\topacity: 0.6;\r\n");
      out.write("\tfilter: alpha(opacity = 60);\r\n");
      out.write("\t-webkit-border-radius: 30px;\r\n");
      out.write("\t-moz-border-radius: 30px;\r\n");
      out.write("\t-o-border-radius: 30px;\r\n");
      out.write("\tborder-radius: 20px;\r\n");
      out.write("\t-webkit-transition: all .25s linear;\r\n");
      out.write("\t-moz-transition: all .25s linear;\r\n");
      out.write("\t-o-transition: all .25s linear;\r\n");
      out.write("\ttransition: all .25s linear;\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#toTop:hover {\r\n");
      out.write("\tbackground: #0d86ea;\r\n");
      out.write("\tborder: 2px solid #0d86ea;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-md-12 nav-wrapper\">\r\n");
      out.write("   <div class=\"navbar-header\" style=\"width: 100%;\">\r\n");
      out.write("   ");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\t");
      if (_jspx_meth_sec_005fauthorize_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t");
      if (_jspx_meth_sec_005fauthorize_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("     \r\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right user-nav\">\r\n");
      out.write("          ");
      if (_jspx_meth_sec_005fauthorize_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            ");
      if (_jspx_meth_sec_005fauthorize_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Top 버튼 -->\r\n");
      out.write("<div id=\"toTop\" align=\"right\" ><i class=\"fa fa-angle-double-up fa-3x\"></i><font size=\"4px\">  Top</font></div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   $(document).ready(function() {\r\n");
      out.write("\t   var sound = new Audio(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/asset/media/alarm.mp3\");\r\n");
      out.write("      $(\"#logoutClick\").click(function() {\r\n");
      out.write("         var flag = confirm(\"로그아웃을 하시겠습니까?\");\r\n");
      out.write("         if (flag == true) {\r\n");
      out.write("            location.href = \"logout.do\";\n");
      out.write("         }//if\r\n");
      out.write("      });//click\r\n");
      out.write("      /* 알림 script */\r\n");
      out.write("    \t  $.ajax({\r\n");
      out.write("\t\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\t\turl:\"requestList.do\",\r\n");
      out.write("\t\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\tif(data != \"\"){\r\n");
      out.write("\t\t\t\t\t\talertify.success('친구 신청이 왔어요!!~~');\r\n");
      out.write("\t\t\t\t\t\tsound.play();\r\n");
      out.write("\t\t\t\t\t\tsetInterval(() => {\r\n");
      out.write("\t\t\t\t\t\t\talertify.success('친구 신청이 왔어요!!~~');\r\n");
      out.write("\t\t\t\t\t\t\tsound.play();\r\n");
      out.write("\t\t\t\t\t\t}, 20000);\r\n");
      out.write("\t\t\t\t\t}//if\r\n");
      out.write("\t\t\t\t}//success\r\n");
      out.write("\t\t\t});//ajax\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\t\turl:\"requestMsg.do\",\r\n");
      out.write("\t\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\tif(data != \"\"){\r\n");
      out.write("\t\t\t\t\t\talertify.success('메세지가 왔어요!!~~');\r\n");
      out.write("\t\t\t\t\t\tsound.play();\r\n");
      out.write("\t\t\t\t\t\tsetInterval(() => {\r\n");
      out.write("\t\t\t\t\t\t\talertify.success('메세지가 왔어요!!~~');\r\n");
      out.write("\t\t\t\t\t\t\tsound.play();\r\n");
      out.write("\t\t\t\t\t\t}, 20000);\r\n");
      out.write("\t\t\t\t\t}//if\r\n");
      out.write("\t\t\t\t}//success\r\n");
      out.write("\t\t\t});//ajax\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#toTop\").bind(\"click\", function() {\r\n");
      out.write("\t\t\t\t$(\"body\").animate({scrollTop : 0}, 200);\r\n");
      out.write("\t\t\t\t});//bind\r\n");
      out.write("\t\t\t$(window).scroll(function() {\r\n");
      out.write("\t\t\t\tif ($(this).scrollTop() != 0) {\r\n");
      out.write("\t\t\t\t\t$('#toTop').fadeIn();\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t$('#toTop').fadeOut();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});//scroll\r\n");
      out.write("      });//ready\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifNotGranted.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f0.setParent(null);
      // /WEB-INF/views/templates/header.jsp(88,3) name = ifNotGranted type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f0.setIfNotGranted("ROLE_MEMBER");
      int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("   \t\t<a class=\"navbar-brand\"><span class = \"fa fa-gift fa-lg\" style = \"margin-top:-5px; margin-left:-17px;\"></span></a>\t\r\n");
        out.write("\t\t<a href=\"home.do\" class=\"navbar-brand\"> <b>YOLO WA</b></a>\t\r\n");
        out.write("\t");
      }
      if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifNotGranted.reuse(_jspx_th_sec_005fauthorize_005f0);
      _jspx_th_sec_005fauthorize_005f0_reused = true;
    } finally {
      if (!_jspx_th_sec_005fauthorize_005f0_reused) {
        _jspx_th_sec_005fauthorize_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_sec_005fauthorize_005f0);
      }
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifAnyGranted.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f1.setParent(null);
      // /WEB-INF/views/templates/header.jsp(93,1) name = ifAnyGranted type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f1.setIfAnyGranted("ROLE_MEMBER,ROLE_ADMIN");
      int _jspx_eval_sec_005fauthorize_005f1 = _jspx_th_sec_005fauthorize_005f1.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("      <div class=\"opener-left-menu is-open\">\r\n");
        out.write("         <span class=\"top\"></span> <span class=\"middle\"></span> <span\r\n");
        out.write("            class=\"bottom\"></span>\r\n");
        out.write("      </div>\r\n");
        out.write("\t");
      }
      if (_jspx_th_sec_005fauthorize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifAnyGranted.reuse(_jspx_th_sec_005fauthorize_005f1);
      _jspx_th_sec_005fauthorize_005f1_reused = true;
    } finally {
      if (!_jspx_th_sec_005fauthorize_005f1_reused) {
        _jspx_th_sec_005fauthorize_005f1.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_sec_005fauthorize_005f1);
      }
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f2 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifAnyGranted.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f2_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f2.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f2.setParent(null);
      // /WEB-INF/views/templates/header.jsp(100,2) name = ifAnyGranted type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f2.setIfAnyGranted("ROLE_MEMBER,ROLE_ADMIN");
      int _jspx_eval_sec_005fauthorize_005f2 = _jspx_th_sec_005fauthorize_005f2.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("\t\t\t\t <a href=\"mainAllContent.do\" class=\"navbar-brand\"> <b>YOLO WA</b></a>\r\n");
        out.write("\t\t\t\t  <ul class=\"nav navbar-nav search-nav\">\r\n");
        out.write("         <li>\r\n");
        out.write("            <div class=\"search\">\r\n");
        out.write("               <span class=\"fa fa-search icon-search\" style=\"font-size: 23px; color:white;\" id=\"searhAll\"></span>\r\n");
        out.write("               <div class=\"form-group form-animate-text\">\r\n");
        out.write("                  <input type=\"text\" class=\"form-text\" id=\"keywordAll\" required>\r\n");
        out.write("                  <span class=\"bar\"></span> <label class=\"label-search\" style = \"color:white;\">Type\r\n");
        out.write("                     anywhere to <b style = \"color:white;\">Search</b>\r\n");
        out.write("                  </label>\r\n");
        out.write("               </div>\r\n");
        out.write("            </div>\r\n");
        out.write("         </li>\r\n");
        out.write("      </ul>\r\n");
        out.write("\t\t");
      }
      if (_jspx_th_sec_005fauthorize_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifAnyGranted.reuse(_jspx_th_sec_005fauthorize_005f2);
      _jspx_th_sec_005fauthorize_005f2_reused = true;
    } finally {
      if (!_jspx_th_sec_005fauthorize_005f2_reused) {
        _jspx_th_sec_005fauthorize_005f2.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_sec_005fauthorize_005f2);
      }
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f3 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifNotGranted.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f3_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f3.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f3.setParent(null);
      // /WEB-INF/views/templates/header.jsp(119,10) name = ifNotGranted type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f3.setIfNotGranted("ROLE_MEMBER");
      int _jspx_eval_sec_005fauthorize_005f3 = _jspx_th_sec_005fauthorize_005f3.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("               <li><a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/loginView.do\"><span class=\"fa fa-power-off\">\r\n");
        out.write("                        LogIn</span></a></li>\r\n");
        out.write("               <li><a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/registerView.do\"><span class=\"fa fa-user\">\r\n");
        out.write("                        SignUp</span></a></li>\r\n");
        out.write("           ");
      }
      if (_jspx_th_sec_005fauthorize_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifNotGranted.reuse(_jspx_th_sec_005fauthorize_005f3);
      _jspx_th_sec_005fauthorize_005f3_reused = true;
    } finally {
      if (!_jspx_th_sec_005fauthorize_005f3_reused) {
        _jspx_th_sec_005fauthorize_005f3.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_sec_005fauthorize_005f3);
      }
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f4 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifAnyGranted.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f4_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f4.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f4.setParent(null);
      // /WEB-INF/views/templates/header.jsp(125,12) name = ifAnyGranted type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f4.setIfAnyGranted("ROLE_MEMBER,ROLE_ADMIN");
      int _jspx_eval_sec_005fauthorize_005f4 = _jspx_th_sec_005fauthorize_005f4.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("               <li class=\"user-name\"><span>");
        if (_jspx_meth_sec_005fauthentication_005f0(_jspx_th_sec_005fauthorize_005f4, _jspx_page_context))
          return true;
        out.write("(<span>");
        if (_jspx_meth_sec_005fauthentication_005f1(_jspx_th_sec_005fauthorize_005f4, _jspx_page_context))
          return true;
        out.write(")</span></li>\r\n");
        out.write("               <li class=\"dropdown avatar-dropdown\"><img\r\n");
        out.write("                  src=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write('/');
        if (_jspx_meth_sec_005fauthentication_005f2(_jspx_th_sec_005fauthorize_005f4, _jspx_page_context))
          return true;
        out.write("\"\r\n");
        out.write("                  class=\"img-circle avatar\" alt=\"user name\" data-toggle=\"dropdown\"\r\n");
        out.write("                  aria-haspopup=\"true\" aria-expanded=\"true\" />\r\n");
        out.write("                  <ul class=\"dropdown-menu user-dropdown\">\r\n");
        out.write("                     <li><a href=\"myMessagePage.do\"><span class=\"fa fa-envelope\"></span>　My Message</a></li>\r\n");
        out.write("                     <li><a href=\"mypage.do?id=");
        if (_jspx_meth_sec_005fauthentication_005f3(_jspx_th_sec_005fauthorize_005f4, _jspx_page_context))
          return true;
        out.write("\"><span class=\"fa fa-user\"></span>　 My Page</a></li>   \r\n");
        out.write("                     <li role=\"separator\" class=\"divider\"></li>\r\n");
        out.write("                     <li><a href=\"#\" id=\"logoutClick\"><span class=\"fa fa-power-off \"></span>　 Logout</a></li>\r\n");
        out.write("                     <li><a href=\"withdrawView.do\" ><span class=\"fa fa-ban \"></span>　 Withdraw</a></li>\r\n");
        out.write("                  </ul>\r\n");
        out.write("               </li>\r\n");
        out.write("               <li><a href=\"#\" class=\"opener-right-menu\"><span\r\n");
        out.write("                     class=\"icon-list\" id=\"tabBtn\"></span></a></li>\r\n");
        out.write("                 ");
      }
      if (_jspx_th_sec_005fauthorize_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifAnyGranted.reuse(_jspx_th_sec_005fauthorize_005f4);
      _jspx_th_sec_005fauthorize_005f4_reused = true;
    } finally {
      if (!_jspx_th_sec_005fauthorize_005f4_reused) {
        _jspx_th_sec_005fauthorize_005f4.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_sec_005fauthorize_005f4);
      }
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f4);
      // /WEB-INF/views/templates/header.jsp(126,43) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setProperty("principal.name");
      int _jspx_eval_sec_005fauthentication_005f0 = _jspx_th_sec_005fauthentication_005f0.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f0);
      _jspx_th_sec_005fauthentication_005f0_reused = true;
    } finally {
      if (!_jspx_th_sec_005fauthentication_005f0_reused) {
        _jspx_th_sec_005fauthentication_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_sec_005fauthentication_005f0);
      }
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f1 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f4);
      // /WEB-INF/views/templates/header.jsp(126,97) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f1.setProperty("principal.grade");
      int _jspx_eval_sec_005fauthentication_005f1 = _jspx_th_sec_005fauthentication_005f1.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f1);
      _jspx_th_sec_005fauthentication_005f1_reused = true;
    } finally {
      if (!_jspx_th_sec_005fauthentication_005f1_reused) {
        _jspx_th_sec_005fauthentication_005f1.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_sec_005fauthentication_005f1);
      }
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f2 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f2_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f2.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f4);
      // /WEB-INF/views/templates/header.jsp(128,59) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f2.setProperty("principal.filePath");
      int _jspx_eval_sec_005fauthentication_005f2 = _jspx_th_sec_005fauthentication_005f2.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f2);
      _jspx_th_sec_005fauthentication_005f2_reused = true;
    } finally {
      if (!_jspx_th_sec_005fauthentication_005f2_reused) {
        _jspx_th_sec_005fauthentication_005f2.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_sec_005fauthentication_005f2);
      }
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f3 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f3_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f3.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f4);
      // /WEB-INF/views/templates/header.jsp(133,47) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f3.setProperty("principal.id");
      int _jspx_eval_sec_005fauthentication_005f3 = _jspx_th_sec_005fauthentication_005f3.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f3);
      _jspx_th_sec_005fauthentication_005f3_reused = true;
    } finally {
      if (!_jspx_th_sec_005fauthentication_005f3_reused) {
        _jspx_th_sec_005fauthentication_005f3.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_sec_005fauthentication_005f3);
      }
    }
    return false;
  }
}
