/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.11
 * Generated at: 2017-06-29 14:57:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.templates;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class rightPopup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-3.2.5.RELEASE.jar", Long.valueOf(1498740093009L));
    _jspx_dependants.put("jar:file:/C:/Users/Moon/Desktop/Saiden/Employment/java-kosta/WAS/final-tomcat/webapps/YOLOWA_FINAL/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1494128633492L));
    _jspx_dependants.put("jar:file:/C:/Users/Moon/Desktop/Saiden/Employment/java-kosta/WAS/final-tomcat/webapps/YOLOWA_FINAL/WEB-INF/lib/spring-security-taglibs-3.2.5.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1408068574000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifAnyGranted;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifAnyGranted = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifAnyGranted.release();
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifAnyGranted.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f0.setParent(null);
      // /WEB-INF/views/templates/rightPopup.jsp(6,0) name = ifAnyGranted type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f0.setIfAnyGranted("ROLE_MEMBER,ROLE_ADMIN");
      int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write('\r');
        out.write('\n');
        if (_jspx_meth_sec_005fauthentication_005f0(_jspx_th_sec_005fauthorize_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("<style>\r\n");
        out.write("textarea {\r\n");
        out.write("\tborder: 0;\r\n");
        out.write("\tmargin: 5px 0;\r\n");
        out.write("\tpadding: 3px;\r\n");
        out.write("\tbackground-color: #fff;\r\n");
        out.write("\twidth: 100%;\r\n");
        out.write("\theight: 80px;\r\n");
        out.write("}\r\n");
        out.write("\r\n");
        out.write("#msgContent{\r\n");
        out.write("\tbackground-color: #fff;\r\n");
        out.write("    overflow: auto;\r\n");
        out.write("    overflow-x: hidden; \r\n");
        out.write("    height: 400px;\r\n");
        out.write("\tmax-height: 400px;\r\n");
        out.write("}\r\n");
        out.write("</style>\r\n");
        out.write("<script src=\"//code.jquery.com/jquery.min.js\"></script>\r\n");
        out.write("<script type=\"text/javascript\">\r\n");
        out.write("$(document).ready(function() {\r\n");
        out.write("\t\r\n");
        out.write("\t//친구 추천 리스트\r\n");
        out.write("\t$(\"#recommend\").click(function() {\r\n");
        out.write("\t\t$(\"#recommandFriends\").show();\r\n");
        out.write("\t\t$(\"#requestFriends\").hide();\r\n");
        out.write("\t\t$.ajax({\r\n");
        out.write("\t\t\ttype:\"get\",\r\n");
        out.write("\t\t\turl:\"recommend.do\",\r\n");
        out.write("\t\t\tdataType:\"json\",\r\n");
        out.write("\t\t\tsuccess:function(data){\r\n");
        out.write("\t\t\t\tvar listTxt = \"\";\r\n");
        out.write("\t\t\t\tfor(var i=0; i < data.length; i++){\r\n");
        out.write("\t\t\t\t\tlistTxt += \"<li><img src=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/\"+data[i].filePath+\" alt='user name'>\";\r\n");
        out.write("\t\t\t\t\tlistTxt += \"<div><h4><b>\"+data[i].name+\"</b></h4></div>\";\r\n");
        out.write("\t\t\t\t\tlistTxt += \"<div class='dot'>\";\r\n");
        out.write("\t\t\t\t\tlistTxt += \"<input type='hidden' value='\"+data[i].id+\"'>\"\r\n");
        out.write("\t\t\t\t\tlistTxt += \"<span class='fa fa-user-plus fa-2x' title='친구신청'></span>\";\r\n");
        out.write("\t\t\t\t\tlistTxt += \"</div></li>\";\r\n");
        out.write("\t\t\t\t}\r\n");
        out.write("\t\t\t\t$(\"#recommendList\").html(listTxt);\r\n");
        out.write("\t\t\t}//success\r\n");
        out.write("\t\t});//ajax\r\n");
        out.write("\t});//click\r\n");
        out.write("\t$(\"#recommendList\").on(\"click\",\"span\",function(){\r\n");
        out.write("\t\tvar id = $(this).prev().val();\r\n");
        out.write("\t\t$.ajax({\r\n");
        out.write("\t\t\ttype:\"get\",\r\n");
        out.write("            url:\"friendAdd.do?id=\"+id,\r\n");
        out.write("            success:function(data){\r\n");
        out.write("            \tif(data == \"ok\"){\r\n");
        out.write("   \t\t\t\t\t$(\"#recommend\").trigger(\"click\");\r\n");
        out.write("   \t\t\t\t}\r\n");
        out.write("   \t\t\t\telse{\r\n");
        out.write("   \t\t\t\t\talert(\"친구 신청이 실패했습니다.\");\r\n");
        out.write("   \t\t\t\t}\r\n");
        out.write("            }//success\r\n");
        out.write("\t\t});//ajax\r\n");
        out.write("\t});//on\r\n");
        out.write("   //// 친구 리스트 & Message\r\n");
        out.write("      $(\"#tabBtn\").click(function() {\r\n");
        out.write("    \t  $(\"#recommandFriends\").hide();\r\n");
        out.write("    \t  $(\"#requestFriends\").hide();\r\n");
        out.write("         $.ajax({\r\n");
        out.write("            type:\"get\",\r\n");
        out.write("            url:\"friendsList.do\",\r\n");
        out.write("            dataType:\"json\",\r\n");
        out.write("            success:function(data){\r\n");
        out.write("               var friendsListTxt = \"\";\r\n");
        out.write("               for(var i=0; i < data.length; i++){\r\n");
        out.write("                  friendsListTxt +=\"<li>\";\r\n");
        out.write("                  friendsListTxt +=\"<img title='메세지창' src=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/\"+data[i].filePath +\" alt=\"+data[i].id+\">\";\r\n");
        out.write("                  friendsListTxt +=\"<div> <h4> <b>\"+data[i].name+\"</b> </h4> </div></div>\";\r\n");
        out.write("                  friendsListTxt +=\"<div class='dot'>\";\r\n");
        out.write("                  friendsListTxt +=\"<input type='hidden' id='hiddenId' value='\"+data[i].id+\"'>\";\r\n");
        out.write("                  friendsListTxt +=\"<span class='fa fa-user-times fa-2x' title='친구삭제'></span></div></li>\";\r\n");
        out.write("               }\r\n");
        out.write("               $(\"#friends\").html(friendsListTxt);\r\n");
        out.write("            }//success\r\n");
        out.write("         });//ajax\r\n");
        out.write("      });//click   \r\n");
        out.write("      \r\n");
        out.write("      $(\"#friends\").on(\"click\",\"span\",function(){\r\n");
        out.write("    \t  var id = $(this).prev().val();\r\n");
        out.write("    \t  $.ajax({\r\n");
        out.write("    \t\t  type:\"get\",\r\n");
        out.write("              url:\"friendDelete.do?id=\"+id,\r\n");
        out.write("              success:function(data){\r\n");
        out.write("            \t  if(data == \"ok\"){\r\n");
        out.write("            \t\t  $(\"#tabBtn\").trigger(\"click\");\r\n");
        out.write("     \t\t\t\t}\r\n");
        out.write("     \t\t\t\telse{\r\n");
        out.write("     \t\t\t\t\talert(\"친구 삭제가 실패했습니다.\");\r\n");
        out.write("     \t\t\t\t}\r\n");
        out.write("              }//success\r\n");
        out.write("    \t  });//ajax\r\n");
        out.write("      });//on\r\n");
        out.write("      \r\n");
        out.write("      $(\"#friends\").on(\"click\",\"img\",function(){\r\n");
        out.write("         //alert($(this).attr(\"alt\"));\r\n");
        out.write("         var indexId = $(this).attr(\"alt\");\r\n");
        out.write("         var chatName= $(this).next().text();\r\n");
        out.write("         $.ajax({\r\n");
        out.write("            type:\"get\",\r\n");
        out.write("            url:\"friendsMsgBox.do?rId=\"+indexId,\r\n");
        out.write("            dataType:\"json\",\r\n");
        out.write("            success:function(data){\r\n");
        out.write("            \tvar msgTxt=\"<input type='hidden' name='receiveId' value=\"+indexId+\">\";\r\n");
        out.write("                //var msgTxt =\"<div id='overflowScroll'>\";\r\n");
        out.write("                $(\"#chatName\").html(chatName);\r\n");
        out.write("                for(var i=0;i<data.msgBox.length;i++){\r\n");
        out.write("                \tvar idVal = \"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\";\r\n");
        out.write("                \tif(idVal==data.msgBox[i].sId){\r\n");
        out.write("                \tmsgTxt +=\"<div class='row msg_container send'>\";\r\n");
        out.write("                    msgTxt +=\"<div class='col-md-9 col-xs-9 bubble'>\";\r\n");
        out.write("                    msgTxt +=\"<div class='messages msg_sent'>\";\r\n");
        out.write("                    msgTxt +=\"<p>\"+data.msgBox[i].message+\"</p>\";\r\n");
        out.write("                    msgTxt +=\"<time datetime='2009-11-13T20:00'>\"+data.msgBox[i].mPostdate+\"</time>  </div>\";\r\n");
        out.write("                      msgTxt +=\"</div>\";\r\n");
        out.write("                      msgTxt +=\" <div class='col-md-3 col-xs-3 avatar-dropdown'>\"\r\n");
        out.write("                      msgTxt +=\"<img src=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write('/');
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.filePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write(" class='img-responsive' alt='user name'>\";\r\n");
        out.write("                      msgTxt +=\"</div> </div>\";\r\n");
        out.write("                \t}\r\n");
        out.write("                \telse{\r\n");
        out.write("                      msgTxt +=\"<div class='row msg_container receive'>\";\r\n");
        out.write("                      msgTxt +=\"<div class='col-md-3 col-xs-3 avatar-dropdown'>\";\r\n");
        out.write("                      msgTxt +=\"<img src=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/\"+data.friend.filePath+\" class='img-responsive' alt='user name'>\";\r\n");
        out.write("                      msgTxt +=\"</div>\";\r\n");
        out.write("                      msgTxt +=\"<div class='col-md-9 col-xs-9 bubble'>\";\r\n");
        out.write("                      msgTxt +=\"<div class='messages msg_receive'>\";\r\n");
        out.write("                      msgTxt +=\"<p>\"+data.msgBox[i].message+\"</p>\";\r\n");
        out.write("                      msgTxt +=\"<time datetime='2009-11-13T20:00'>\"+data.msgBox[i].mPostdate+\"</time>  </div>\";\r\n");
        out.write("                      msgTxt +=\"</div> </div>\";\r\n");
        out.write("                \t}\r\n");
        out.write("                }\r\n");
        out.write("                $(\"#msgContent\").html(msgTxt); \r\n");
        out.write("                $(\"#friendsContainer\").hide();  \r\n");
        out.write("                $(\"#recommandFriends\").hide();\r\n");
        out.write("                $(\"#requestFriends\").hide();\r\n");
        out.write("                $(\"#msgContainer\").show();\r\n");
        out.write("            },//success\r\n");
        out.write("            complete : function(){\r\n");
        out.write("    \t    \tvar el = document.getElementById(\"msgContent\"); \r\n");
        out.write("  \t\t\t\tel.scrollTop = el.scrollHeight;\r\n");
        out.write("    \t      }\r\n");
        out.write("         });//ajax \r\n");
        out.write("      });\r\n");
        out.write("      $(\"#closeMsgBox\").click(function(){\r\n");
        out.write("    \t  $(\"#friendsContainer\").show();  \r\n");
        out.write("    \t  $(\"#recommandFriends\").hide();\r\n");
        out.write("    \t  $(\"#requestFriends\").hide();\r\n");
        out.write("          $(\"#msgContainer\").hide();\r\n");
        out.write("      });// close click event\r\n");
        out.write("      \r\n");
        out.write("      \r\n");
        out.write("      $(\"#chatTxt\").keypress(function(e){\r\n");
        out.write("    \t\tif(e.which==13){\r\n");
        out.write("    \t  //alert($(\"#chatTxt\").val()); // TextArea 글\r\n");
        out.write("    \t  //alert($(\"#friends img\").attr(\"alt\")); // 보낼 사람 Id\r\n");
        out.write("    \t  var sendMsg = $(\"#chatTxt\").val();\r\n");
        out.write("    \t  var receiveId =$(\":input[name=receiveId]\").val();\r\n");
        out.write("    \t  var sendId = \"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\";\r\n");
        out.write("    \t  //alert($(\":input[name=receiveId]\").val());\r\n");
        out.write("    \t  //alert(\"받는 사람\"+receiveId);\r\n");
        out.write("    \t  if(sendMsg ==\"\"){\r\n");
        out.write("    \t\t  alert(\"메세지를 입력하세요\")\r\n");
        out.write("    \t  }else{\r\n");
        out.write("    \t\t  $(\"#chatTxt\").val(\"\");\r\n");
        out.write("    \t\t  $.ajax({\r\n");
        out.write("            \t  type:\"post\",\r\n");
        out.write("            \t  url:\"sendMessage.do\",\r\n");
        out.write("           \t   \t  data:\"sId=\"+sendId+\"&rId=\"+receiveId+\"&message=\"+sendMsg,\r\n");
        out.write("          \t      success:function(data){\r\n");
        out.write("           \t\t\t\tif(data == \"ok\"){\r\n");
        out.write("           \t\t\t\t\t$(\"#friends img[alt=\"+receiveId+\"]\").trigger(\"click\");\r\n");
        out.write("           \t\t\t\t}\r\n");
        out.write("           \t\t\t\telse{\r\n");
        out.write("           \t\t\t\t\talert(\"메세지 전송 실패했습니다.\");\r\n");
        out.write("           \t\t\t\t}\r\n");
        out.write("           \t\t\t\t$(\"#chatTxt\").val(\"\");\t\r\n");
        out.write("        \t      }//success\r\n");
        out.write("    \t       });//ajax   \t \r\n");
        out.write("    \t \t }\r\n");
        out.write("    \t}\r\n");
        out.write("      });// chatBtn click\r\n");
        out.write("    \r\n");
        out.write("      //받은 친구신청 리스트\r\n");
        out.write("      $(\"#checkRequest\").click(function() {\r\n");
        out.write("  \t\t$(\"#requestFriends\").show();\r\n");
        out.write("  \t\t$.ajax({\r\n");
        out.write("  \t\t\ttype:\"get\",\r\n");
        out.write("  \t\t\turl:\"requestList.do\",\r\n");
        out.write("  \t\t\tdataType:\"json\",\r\n");
        out.write("  \t\t\tsuccess:function(data){\r\n");
        out.write("  \t\t\t\tvar listTxt = \"\";\r\n");
        out.write("  \t\t\t\tfor(var i=0; i < data.length; i++){\r\n");
        out.write("  \t\t\t\t\tlistTxt += \"<li><img src=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/\"+data[i].filePath+\" alt='user name'>\";\r\n");
        out.write("  \t\t\t\t\tlistTxt += \"<div><h4><b>\"+data[i].name+\"</b></h4></div>\";\r\n");
        out.write("  \t\t\t\t\tlistTxt += \"<div class='dot'>\";\r\n");
        out.write("  \t\t\t\t\tlistTxt += \"<input type='hidden' id='hiddenId' value='\"+data[i].id+\"'>\"\r\n");
        out.write("  \t\t\t\t\tlistTxt += \"<span class='fa fa-user-plus fa-2x' title='친구추가'></span>\";\r\n");
        out.write("  \t\t\t\t\tlistTxt += \"</div></li>\";\r\n");
        out.write("  \t\t\t\t}\r\n");
        out.write("  \t\t\t\t$(\"#requestList\").html(listTxt);\r\n");
        out.write("  \t\t\t}//success\r\n");
        out.write("  \t\t});//ajax\r\n");
        out.write("  \t});//click\r\n");
        out.write("  \t$(\"#requestList\").on(\"click\",\"span\",function(){\r\n");
        out.write("\t\tvar id = $(this).prev().val();\r\n");
        out.write("\t\t$.ajax({\r\n");
        out.write("\t\t\ttype:\"get\",\r\n");
        out.write("            url:\"friendCheck.do?id=\"+id,\r\n");
        out.write("            success:function(data){\r\n");
        out.write("            \tif(data == \"ok\"){\r\n");
        out.write("   \t\t\t\t\t$(\"#checkRequest\").trigger(\"click\");\r\n");
        out.write("   \t\t\t\t}\r\n");
        out.write("   \t\t\t\telse{\r\n");
        out.write("   \t\t\t\t\talert(\"친구 추가가 실패했습니다.\");\r\n");
        out.write("   \t\t\t\t}\r\n");
        out.write("            }//success\r\n");
        out.write("\t\t});//ajax\r\n");
        out.write("\t});//on\r\n");
        out.write("});//ready\r\n");
        out.write("</script>\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("<ul class=\"nav nav-tabs\" >\r\n");
        out.write("   <li>\r\n");
        out.write("      <a data-toggle=\"tab\" href=\"#right-menu-user\">\r\n");
        out.write("         <span class=\"fa fa-comment-o fa-2x\" title=\"친구리스트\"></span>\r\n");
        out.write("      </a>\r\n");
        out.write("   </li>\r\n");
        out.write("   <li>\r\n");
        out.write("      <a data-toggle=\"tab\" href=\"#right-menu-userRecommend\">\r\n");
        out.write("         <span class=\"icon-people fa-2x\" id=\"recommend\" title=\"친구추천\"></span>\r\n");
        out.write("      </a>\r\n");
        out.write("   </li>\r\n");
        out.write("   <li>\r\n");
        out.write("      <a data-toggle=\"tab\" href=\"#right-menu-friendRequest\">\r\n");
        out.write("         <span class=\"icon-user-follow fa-2x\" id=\"checkRequest\" title=\"받은친구신청\"></span>\r\n");
        out.write("      </a>\r\n");
        out.write("   </li>\r\n");
        out.write("</ul>\r\n");
        out.write("\r\n");
        out.write("<!--  오른쪽 커피 누르면 나오는 메뉴 바 -->\r\n");
        out.write("<div class=\"tab-content\">\r\n");
        out.write("   ");
        if (_jspx_meth_c_005fset_005f0(_jspx_th_sec_005fauthorize_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("   <!--  커피 바 영역-->\r\n");
        out.write("   <div id=\"right-menu-user\" class=\"tab-pane fade in active\">\r\n");
        out.write("    \r\n");
        out.write("      <!--  친구 목록 -->\r\n");
        out.write("      <div class=\"user col-md-12\" id=\"friendsContainer\">\r\n");
        out.write("         <ul class=\"nav nav-list\" id=\"friends\">\r\n");
        out.write("         </ul>\r\n");
        out.write("      </div>\r\n");
        out.write("      \r\n");
        out.write("      <div class=\"col-md-12 chatbox\" id =\"msgContainer\">\r\n");
        out.write("         <!--  한 세트 -->\r\n");
        out.write("         <div class=\"col-md-12\">\r\n");
        out.write("            <a href=\"#\" class=\"close-chat\" id=\"closeMsgBox\">X</a>\r\n");
        out.write("            <h4 id=\"chatName\">\r\n");
        out.write("               <!--  채팅 주인 이름 -->\r\n");
        out.write("            </h4>\r\n");
        out.write("         </div>\r\n");
        out.write("         <div class=\"chat-area\" >\r\n");
        out.write("            <div class=\"chat-area-content\" >\r\n");
        out.write("               <div class=\"msg_container_base\" id=\"msgContent\">\r\n");
        out.write("               </div>\r\n");
        out.write("                 <textarea id=\"chatTxt\" placeholder=\"메세지를 입력하세요...\"></textarea>\r\n");
        out.write("            </div>\r\n");
        out.write("         </div>\r\n");
        out.write("      <!--    <div class=\"user-list\"  id=\"chatBox\">\r\n");
        out.write("            \r\n");
        out.write("              <input type=\"button\" value=\"Send\" id=\"chatBtn\">\r\n");
        out.write("          </div> -->\r\n");
        out.write("      </div>\r\n");
        out.write("      \r\n");
        out.write("      \r\n");
        out.write("   </div>\r\n");
        out.write("  \r\n");
        out.write("   <!--  메세지 끝 -->\r\n");
        out.write("   <!-- 친구추천 -->\r\n");
        out.write("   <div id=\"right-menu-userRecommend\" class=\"tab-pane fade in active\">\r\n");
        out.write("      <!-- 추천리스트 -->\r\n");
        out.write("      <div class=\"user col-md-12\" id=\"recommandFriends\">\r\n");
        out.write("         <h4 align=\"center\"><b>친구 추천</b></h4><hr>\r\n");
        out.write("         <ul class=\"nav nav-list\" id=\"recommendList\"></ul>\r\n");
        out.write("      </div>\r\n");
        out.write("   </div>\r\n");
        out.write("   <!-- 받은 친구 신청 리스트 -->\r\n");
        out.write("   <div id=\"right-menu-friendRequest\" class=\"tab-pane fade in active\">\r\n");
        out.write("      <div class=\"user col-md-12\" id=\"requestFriends\">\r\n");
        out.write("         <h4 align=\"center\"><b>받은 친구 신청</b></h4><hr>\r\n");
        out.write("         <ul class=\"nav nav-list\" id=\"requestList\"></ul>\r\n");
        out.write("      </div>\r\n");
        out.write("   </div>\r\n");
        out.write("   </div>\r\n");
        out.write("<!-- end: right menu -->\r\n");
      }
      if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fifAnyGranted.reuse(_jspx_th_sec_005fauthorize_005f0);
      _jspx_th_sec_005fauthorize_005f0_reused = true;
    } finally {
      if (!_jspx_th_sec_005fauthorize_005f0_reused) {
        _jspx_th_sec_005fauthorize_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_sec_005fauthorize_005f0);
      }
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f0);
      // /WEB-INF/views/templates/rightPopup.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setVar("user");
      // /WEB-INF/views/templates/rightPopup.jsp(7,0) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setProperty("principal");
      int _jspx_eval_sec_005fauthentication_005f0 = _jspx_th_sec_005fauthentication_005f0.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f0);
      _jspx_th_sec_005fauthentication_005f0_reused = true;
    } finally {
      if (!_jspx_th_sec_005fauthentication_005f0_reused) {
        _jspx_th_sec_005fauthentication_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_sec_005fauthentication_005f0);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f0);
      // /WEB-INF/views/templates/rightPopup.jsp(254,3) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/templates/rightPopup.jsp(254,3) '${requestScope.friendsList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${requestScope.friendsList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/templates/rightPopup.jsp(254,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("map");
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      if (!_jspx_th_c_005fset_005f0_reused) {
        _jspx_th_c_005fset_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fset_005f0);
      }
    }
    return false;
  }
}
