/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.11
 * Generated at: 2017-06-29 14:58:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registerView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Moon/Desktop/Saiden/Employment/java-kosta/WAS/final-tomcat/webapps/YOLOWA_FINAL/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1494128633492L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"http://fonts.googleapis.com/css?family=Roboto:400,100,300,500\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/font-awesome/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/css/form-elements.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css\">\r\n");
      out.write("<!-- Favicon and touch icons -->\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\"\r\n");
      out.write("   href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/ico/apple-touch-icon-144-precomposed.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\"\r\n");
      out.write("   href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/ico/apple-touch-icon-114-precomposed.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\"\r\n");
      out.write("   href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/ico/apple-touch-icon-72-precomposed.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon-precomposed\"\r\n");
      out.write("   href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/ico/apple-touch-icon-57-precomposed.png\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".top-content {\r\n");
      out.write("   width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".inner-bg {\r\n");
      out.write("   margin: auto;\r\n");
      out.write("   width: 1000px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#loginForm {\r\n");
      out.write("   margin: auto;\r\n");
      out.write("   width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#loginForm #secondLoginForm {\r\n");
      out.write("   margin: auto;\r\n");
      out.write("   width: 1000px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#loginForm #secondLoginForm #lForm {\r\n");
      out.write("   margin: auto;\r\n");
      out.write("   width: 450px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-form .form-group .form-username {\r\n");
      out.write("   display: inline;\r\n");
      out.write("   width: 65%;\r\n");
      out.write("   margin-left: 80px;\r\n");
      out.write("   height: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-form .form-group .form-password {\r\n");
      out.write("   display: inline;\r\n");
      out.write("   width: 65%;\r\n");
      out.write("   margin-left: 59px;\r\n");
      out.write("   height: 50px;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#blankDiv {\r\n");
      out.write("   margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-form .form-group .phoneInput1{\r\n");
      out.write("   margin-left: 58px;\r\n");
      out.write("   width: 80px;\r\n");
      out.write("   height: 50px;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write(".login-form .form-group .phoneInput2{\r\n");
      out.write("   margin-left: 5px;\r\n");
      out.write("   width: 80px;\r\n");
      out.write("   height: 50px;\r\n");
      out.write("}\r\n");
      out.write(".login-form .form-group .phoneInput3{\r\n");
      out.write("   margin-left: 5px;\r\n");
      out.write("   width: 80px;\r\n");
      out.write("   height: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-form .form-group .check-form{\r\n");
      out.write("    margin-left: 55px;\r\n");
      out.write("    width: 20px;\r\n");
      out.write("    height: 20px;\r\n");
      out.write("} \r\n");
      out.write(".login-form .form-group .form-address{\r\n");
      out.write("   margin-left: 75px;\r\n");
      out.write("   width: 130px;\r\n");
      out.write("}\r\n");
      out.write(".socialForm{\r\n");
      out.write("   margin-left: 10px;\r\n");
      out.write("   padding-bottom: 5px;\r\n");
      out.write("   height: 50px;\r\n");
      out.write("}\r\n");
      out.write(".form-group .addressText{\r\n");
      out.write("      margin-left: 140px;\r\n");
      out.write("      width: 65%;\r\n");
      out.write("}\r\n");
      out.write("label[for=\"c\"] {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        bottom: 6px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"//code.jquery.com/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("      $(document).ready(function() {\r\n");
      out.write("         \r\n");
      out.write("         $(\"#sample6_postcode\").click(function(){\r\n");
      out.write("            $(\"#searchBtn\").trigger(\"click\");\r\n");
      out.write("         });\r\n");
      out.write("         var checkResultId=\"\";   \r\n");
      out.write("          $(\"#signUp\").click(function(){\r\n");
      out.write("               if(checkResultId==\"\"){\r\n");
      out.write("                  alert(\"아이디 중복확인을 하세요\");\r\n");
      out.write("                  return false;\r\n");
      out.write("               }\r\n");
      out.write("               if($(\"#id\").val()==\"\"){\r\n");
      out.write("                  alert(\"아이디를 입력하세요\");\r\n");
      out.write("                  return false;\r\n");
      out.write("               }\r\n");
      out.write("               if($(\"#password\").val()==\"\"){\r\n");
      out.write("                  alert(\"패스워드를 입력하세요\");\r\n");
      out.write("                  return false;\r\n");
      out.write("               }\r\n");
      out.write("               if($(\"#name\").val()==\"\"){\r\n");
      out.write("                  alert(\"이름을 입력하세요\");\r\n");
      out.write("                  return false;\r\n");
      out.write("               }\r\n");
      out.write("               if($(\"#phone2\").val() ==\"\" || $(\"#phone3\").val()==\"\"){\r\n");
      out.write("                  alert(\"핸드폰 번호를 입력하세요.\");\r\n");
      out.write("                  return false;\r\n");
      out.write("               }\r\n");
      out.write("               if($(\"#phone2\").val().length < 4 || $(\"#phone2\").val().length > 4){\r\n");
      out.write("\t\t\t\t\talert(\"정확한 핸드폰 번호를 입력하세요.\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif($(\"#phone3\").val().length < 4 || $(\"#phone3\").val().length > 4){\r\n");
      out.write("\t\t\t\t\talert(\"정확한 핸드폰 번호를 입력하세요.\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("               if(isNaN(parseInt($(\"#phone2\").val()))==true || isNaN(parseInt($(\"#phone3\").val()))==true){\r\n");
      out.write("                  alert(\"숫자를 입력하세요.\");\r\n");
      out.write("                  return false;\r\n");
      out.write("               }\r\n");
      out.write("               var addressDetail =$(\"#sample6_postcode\").val();\r\n");
      out.write("               addressDetail +=\"/\"+$(\"#sample6_address\").val();\r\n");
      out.write("               addressDetail +=\"/\"+$(\"#sample6_address2\").val();\r\n");
      out.write("               $(\"#addressTxt\").val(addressDetail);\r\n");
      out.write("               \r\n");
      out.write("               if($(\":input[name=checkbox_category]:checked\").length<1||\r\n");
      out.write("                     $(\":input[name=checkbox_category]:checked\").length>3){\r\n");
      out.write("                  alert(\"카테고리를 1개 이상 3개 이하 선택하세요\");\r\n");
      out.write("                  return false;\r\n");
      out.write("               }\r\n");
      out.write("                var category=$(\":input[name=checkbox_category]:checked\");\r\n");
      out.write("               var tmp=\"\";\r\n");
      out.write("               for(var i=0;i<category.length;i++){\r\n");
      out.write("                  tmp +=\"<input type='hidden'name='cNo' value=\"+$(category[i]).val()+\">\"; \r\n");
      out.write("               }  \r\n");
      out.write("               var phoneNumber = \"010\";\r\n");
      out.write("               phoneNumber +=\"-\"+$(\"#phone2\").val();\r\n");
      out.write("               phoneNumber +=\"-\"+$(\"#phone3\").val();\r\n");
      out.write("               $(\"#phoneToString\").val(phoneNumber);\r\n");
      out.write("               $(\"#category\").html(tmp);\r\n");
      out.write("               $(\"#form-signin\").submit();   \r\n");
      out.write("         }); //click\r\n");
      out.write("         // 아이디 중복 체크\r\n");
      out.write("         $(\":input[name=id]\").keyup(function(){\r\n");
      out.write("            var id=$(this).val().trim();\r\n");
      out.write("            if(id.length<4 || id.length>10){\r\n");
      out.write("               $(\"#idCheckView\").html(\"아이디는 4자이상 10자 이하여야 함!\").css(\r\n");
      out.write("                     \"color\",\"pink\");\r\n");
      out.write("               checkResultId=\"\";\r\n");
      out.write("               return;\r\n");
      out.write("            }         \r\n");
      out.write("            $.ajax({\r\n");
      out.write("               type:\"POST\",\r\n");
      out.write("               url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/idcheckAjax.do\",         \r\n");
      out.write("               data:\"id=\"+id,   \r\n");
      out.write("               success:function(data){                  \r\n");
      out.write("                  if(data==\"fail\"){\r\n");
      out.write("                  $(\"#idCheckView\").html(id+\" 사용불가!\").css(\"color\",\"red\");\r\n");
      out.write("                     checkResultId=\"\";\r\n");
      out.write("                  }else{                  \r\n");
      out.write("                     $(\"#idCheckView\").html(id+\" 사용가능!\").css(\"color\",\r\n");
      out.write("                           \"white\");      \r\n");
      out.write("                     checkResultId=id;\r\n");
      out.write("                  }               \r\n");
      out.write("               }//callback         \r\n");
      out.write("            });//ajax\r\n");
      out.write("         });//keyup\r\n");
      out.write("      }); //ready\r\n");
      out.write("      function sample6_execDaumPostcode() {\r\n");
      out.write("           new daum.Postcode({\r\n");
      out.write("               oncomplete: function(data) {\r\n");
      out.write("                   // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                   // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("                   // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                   var fullAddr = ''; // 최종 주소 변수\r\n");
      out.write("                   var extraAddr = ''; // 조합형 주소 변수\r\n");
      out.write("\r\n");
      out.write("                   // 사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("                   if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("                       fullAddr = data.roadAddress;\r\n");
      out.write("\r\n");
      out.write("                   } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("                       fullAddr = data.jibunAddress;\r\n");
      out.write("                   }\r\n");
      out.write("\r\n");
      out.write("                   // 사용자가 선택한 주소가 도로명 타입일때 조합한다.\r\n");
      out.write("                   if(data.userSelectedType === 'R'){\r\n");
      out.write("                       //법정동명이 있을 경우 추가한다.\r\n");
      out.write("                       if(data.bname !== ''){\r\n");
      out.write("                           extraAddr += data.bname;\r\n");
      out.write("                       }\r\n");
      out.write("                       // 건물명이 있을 경우 추가한다.\r\n");
      out.write("                       if(data.buildingName !== ''){\r\n");
      out.write("                           extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                       }\r\n");
      out.write("                       // 조합형주소의 유무에 따라 양쪽에 괄호를 추가하여 최종 주소를 만든다.\r\n");
      out.write("                       fullAddr += (extraAddr !== '' ? ' ('+ extraAddr +')' : '');\r\n");
      out.write("                   }\r\n");
      out.write("\r\n");
      out.write("                   // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                   document.getElementById('sample6_postcode').value = data.zonecode; //5자리 새우편번호 사용\r\n");
      out.write("                   document.getElementById('sample6_address').value = fullAddr;\r\n");
      out.write("\r\n");
      out.write("                   // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("                   document.getElementById('sample6_address2').focus();\r\n");
      out.write("               }\r\n");
      out.write("           }).open();\r\n");
      out.write("       }\r\n");
      out.write("   </script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("   <!-- Top content -->\r\n");
      out.write("   <div class=\"top-content\">\r\n");
      out.write("      <div class=\"inner-bg\">\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-sm-8 col-sm-offset-2 text\">\r\n");
      out.write("               <h1>You Only Live Once</h1>\r\n");
      out.write("               <div class=\"description\">\r\n");
      out.write("                  <p>\r\n");
      out.write("                     <strong>YOLO</strong> 라는 뜻은 <strong>\"You Only Live Once\"</strong>\r\n");
      out.write("                     입니다.<br> 보다 더 좋은 서비스를 위해 저희는 고객의 입장에서 항상 생각 합니다. <br> <a\r\n");
      out.write("                        href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home.do\"><strong>YoloWa</strong></a>\r\n");
      out.write("                     ← 누르시면 이전 페이지로 이동 합니다.<br>\r\n");
      out.write("                  </p>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"row\" id=\"blankDiv\"></div>\r\n");
      out.write("         <div class=\"row\" id=\"loginForm\">\r\n");
      out.write("            <div id=\"secondLoginForm\">\r\n");
      out.write("               <div class=\"form-box\" id=\"lForm\">\r\n");
      out.write("                  <div class=\"form-top\">\r\n");
      out.write("                     <div class=\"form-top-left\">\r\n");
      out.write("                        <h3>New Create Account</h3>\r\n");
      out.write("                        <p><strong>YoloWa</strong> 페이지는 회원가입이 필수 입니다.</p>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"form-top-right\">\r\n");
      out.write("                        <i class=\"fa fa-key\"></i>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"form-bottom\">\r\n");
      out.write("                     <form role=\"form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/registerMember.do\" method=\"post\"\r\n");
      out.write("                        class=\"login-form\" id=\"form-signin\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                           <font style=\"font-size: 20px; color: white\"> 아이디</font><input\r\n");
      out.write("                              type=\"text\" name=\"id\" placeholder=\"ID\"\r\n");
      out.write("                              class=\"form-username form-control\" id=\"form-username\">\r\n");
      out.write("                           <span id=\"idCheckView\" style=\"margin-top: 10px\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                           <font style=\"font-size: 20px; color: white\"> 비밀번호</font><input\r\n");
      out.write("                              type=\"password\" name=\"password\" placeholder=\"Password\"\r\n");
      out.write("                              class=\"form-password form-control\" >\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                           <font style=\"font-size: 20px; color: white\"> 이름　</font><input\r\n");
      out.write("                              type=\"text\" name=\"name\" placeholder=\"Name\"\r\n");
      out.write("                              class=\"form-username form-control\" >\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                           <font style=\"font-size: 20px; color: white\">전화번호</font>\r\n");
      out.write("                           <input type=\"text\" name=\"phone1\"  readonly=\"readonly\" value=\"010\" class=\"form-username phoneInput1\">\r\n");
      out.write("                           <input type=\"text\" id=\"phone2\"  class=\"form-username phoneInput2\">\r\n");
      out.write("                           <input type=\"text\" id=\"phone3\"  class=\"form-username phoneInput3\">\r\n");
      out.write("                           <input type=\"hidden\" name=\"phone\"  id=\"phoneToString\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                           <font style=\"font-size: 20px; color: white\"> 주소　</font>\r\n");
      out.write("                           <input type=\"text\" id=\"sample6_postcode\" placeholder=\"우편번호\" class=\"form-username form-address\" >\r\n");
      out.write("                           <input type=\"button\" onclick=\"sample6_execDaumPostcode()\" \r\n");
      out.write("                           value=\"우편번호 찾기\" class=\"btn socialForm\" id=\"searchBtn\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                           <input type=\"text\" id=\"sample6_address\" placeholder=\"주소\" class=\"addressText\">\r\n");
      out.write("                           <div class=\"form-group\"></div>\r\n");
      out.write("                           <input type=\"text\" id=\"sample6_address2\" placeholder=\"상세주소\" class=\"addressText\">\r\n");
      out.write("                           <input type=\"hidden\" name=\"address\" id=\"addressTxt\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                              <font style=\"font-size: 20px;\" color=\"white\"> 카테고리</font><br>\r\n");
      out.write("                              <hr>\r\n");
      out.write("                           <div class=\"checkBoxStyle\">\r\n");
      out.write("                           ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                           </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"category\"></div>\r\n");
      out.write("                        <button type=\"submit\" class=\"btn\" id=\"signUp\">Create Account !</button>\r\n");
      out.write("                  </form>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   <!-- Footer -->\r\n");
      out.write("   <footer>\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("         <div class=\"col-sm-8 col-sm-offset-2\">\r\n");
      out.write("            <div class=\"footer-border\"></div>\r\n");
      out.write("            <p>\r\n");
      out.write("               Made by Kosta145 <a\r\n");
      out.write("                  href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home.do\"><strong>YoloWa</strong></a>\r\n");
      out.write("               having a lot of fun. <i class=\"fa fa-smile-o\"></i>\r\n");
      out.write("            </p>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </footer>\r\n");
      out.write("   <!-- Javascript -->\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/jquery.backstretch.min.js\"></script>\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/scripts.js\"></script>\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/member/registerView.jsp(326,27) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/registerView.jsp(326,27) '${categoryList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${categoryList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/member/registerView.jsp(326,27) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("category");
      // /WEB-INF/views/member/registerView.jsp(326,27) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("index");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                           <input type=\"checkbox\" name=\"checkbox_category\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.cNO}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"  class=\"check-form\" ><label for=\"c\"><font style=\"font-size: 16px; color: white;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.cType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</font></label> \r\n");
            out.write("                              ");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("                           ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      if (!_jspx_th_c_005fforEach_005f0_reused) {
        _jspx_th_c_005fforEach_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fforEach_005f0);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/member/registerView.jsp(328,30) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${index.count ==3 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                 <br>\r\n");
          out.write("                              ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      if (!_jspx_th_c_005fif_005f0_reused) {
        _jspx_th_c_005fif_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fif_005f0);
      }
    }
    return false;
  }
}
